## Here is a template for view individual model stats. 
We focus on GPT-5 (mini) as that is the cheapest GPT model on the apex_2025

In [68]:
import pandas as pd
DATA_PATH = "data/all_answers_pd/all_answers_pruned.csv"
df = pd.read_csv(DATA_PATH)
df.head()

,Unnamed: 0,index,parsed_answer,correct,competition,unique_problem_label,problem_idx,output_cost_per_tokens,input_cost_per_tokens,cost,output_tokens,input_tokens,answer,user_message,idx_answer,model_config,model_name,gold_answer,ten_percent_quantile
0,0,0,4048,False,MathArena/apex_2025_outputs,MathArena/apex_2025_outputs: 12,12,15.0,3.0,0.337827,22492.0,149.0,"Looking at this problem, I need to find the mi...","Please reason step by step, and put your final...",0,anthropic/claude-sonnet-45,Claude-Sonnet-4.5 (Think),2112,1
1,1,1,4048,False,MathArena/apex_2025_outputs,MathArena/apex_2025_outputs: 12,12,15.0,3.0,0.285177,18982.0,149.0,"Looking at this problem, I need to find the mi...","Please reason step by step, and put your final...",1,anthropic/claude-sonnet-45,Claude-Sonnet-4.5 (Think),2112,1
2,2,2,4048,False,MathArena/apex_2025_outputs,MathArena/apex_2025_outputs: 12,12,15.0,3.0,0.387807,25824.0,149.0,"Looking at this problem, I need to find the mi...","Please reason step by step, and put your final...",2,anthropic/claude-sonnet-45,Claude-Sonnet-4.5 (Think),2112,1
3,3,3,4048,False,MathArena/apex_2025_outputs,MathArena/apex_2025_outputs: 12,12,15.0,3.0,0.342972,22835.0,149.0,"Looking at this problem, I need to find the mi...","Please reason step by step, and put your final...",3,anthropic/claude-sonnet-45,Claude-Sonnet-4.5 (Think),2112,1
4,4,4,4048,False,MathArena/apex_2025_outputs,MathArena/apex_2025_outputs: 12,12,15.0,3.0,0.317262,21121.0,149.0,"Looking at this problem, I need to find the mi...","Please reason step by step, and put your final...",4,anthropic/claude-sonnet-45,Claude-Sonnet-4.5 (Think),2112,1

In [69]:
MODEL_NAME = "model_name"
moldel_names = list(df[MODEL_NAME].unique())
moldel_names

['Claude-Sonnet-4.5 (Think)',
 'DeepSeek-v3.1 (Think)',
 'DeepSeek-R1-0528',
 'DeepSeek-v3.2 (Think)',
 'gemini-2.5-pro',
 'GPT-5 (high)',
 'GPT OSS 120B (high)',
 'GPT-5-mini (high)',
 'GPT-5 (High) Agent',
 'GLM 4.6',
 'GLM 4.5',
 'Qwen3-235B-2507-Think',
 'Grok 4 Fast (Reasoning)',
 'Grok 4',
 'Claude-Opus-4.0 (Think)',
 'Claude-3.7-Sonnet (Think)',
 'Claude-3.5-Sonnet',
 'DeepSeek-R1-Distill-14B',
 'DeepSeek-R1-Distill-32B',
 'DeepSeek-R1-Distill-1.5B',
 'DeepSeek-V3',
 'DeepSeek-R1-Distill-70B',
 'DeepSeek-V3-03-24',
 'DeepSeek-R1',
 'Llama-4-Maverick',
 'gemini-2.5-flash (think)',
 'gemini-2.5-pro-05-06',
 'gemini-2.0-pro',
 'gemini-2.0-flash',
 'gemini-2.0-flash-thinking',
 'GPT OSS 20B (high)',
 'o3 (high)',
 'o3-mini (low)',
 'o3-mini (medium)',
 'o4-mini (medium)',
 'o4-mini (high)',
 'o4-mini (low)',
 'o1 (medium)',
 'GPT-5-nano (high)',
 'gpt-4o',
 'o3-mini (high)',
 'GLM 4.5 Air',
 'LIMO',
 's1.1-32B',
 'K2-Think',
 'OpenThinker-32B',
 'Phi-4-reasoning-plus',
 'Qwen3-235B-A22B',
 'QwQ-32B-Preview',
 'Qwen3-30B-A3B',
 'QwQ-32B',
 'Grok 3 Mini (low)',
 'Grok 3 Mini (high)',
 'gemini-2.5-pro*',
 'GLM 4.5V',
 'Qwen3-VL-235B Instruct']

In [70]:
gpt5_mini = "gpt-4o"

df_new = df[df[MODEL_NAME]==gpt5_mini]
df_new

,Unnamed: 0,index,parsed_answer,correct,competition,unique_problem_label,problem_idx,output_cost_per_tokens,input_cost_per_tokens,cost,output_tokens,input_tokens,answer,user_message,idx_answer,model_config,model_name,gold_answer,ten_percent_quantile
5868,5868,5868,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.007622,720.0,169.0,"To solve this problem, we need to analyze the ...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,248,2
5869,5869,5869,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.008783,836.0,169.0,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...",1,openai/gpt-4o,gpt-4o,248,2
5870,5870,5870,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.010582,1016.0,169.0,"To solve this problem, we begin by analyzing t...","Please reason step by step, and put your final...",2,openai/gpt-4o,gpt-4o,248,2
5871,5871,5871,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.010802,1038.0,169.0,"First, we need to analyze the sequence \( x_1,...","Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,248,2
5872,5872,5872,960,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 23,23,10.0,2.5,0.012202,1141.0,317.0,To determine when the greedy algorithm succeed...,"Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,610,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15823,15823,15823,"[13,0]",False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 10,10,10.0,2.5,0.010315,1003.0,114.0,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,"\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}",3
15824,15824,15824,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.005293,512.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15825,15825,15825,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.006683,651.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",1,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15826,15826,15826,1/2017,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.007923,775.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",2,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15827,15827,15827,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.007313,714.0,69.0,To find the remainder \( r \) when \( 2017^{20...,"Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5

## Find all problems GPT5-mini could not solve

In [71]:
df_new[df_new["unique_problem_label"] == "MathArena/apex_2025_outputs: 11"]

Empty DataFrame
Columns: [Unnamed: 0, index, parsed_answer, correct, competition, unique_problem_label, problem_idx, output_cost_per_tokens, input_cost_per_tokens, cost, output_tokens, input_tokens, answer, user_message, idx_answer, model_config, model_name, gold_answer, ten_percent_quantile]
Index: []

In [72]:
CORRECT = "correct"
falses = df_new[df_new[CORRECT]==False]["unique_problem_label"]
trues = df_new[df_new[CORRECT] == True]["unique_problem_label"]
only_false = set(falses).difference(trues)
df_new_false = df_new[df_new["unique_problem_label"].isin(only_false)]
mask = ~df_new_false["unique_problem_label"].str.contains("kangaroo", case=False, na=False)
df_new_false = df_new_false[mask]
example = df_new_false.tail(15)[["parsed_answer", "unique_problem_label", "answer", "user_message", "gold_answer"]]
example

,parsed_answer,unique_problem_label,answer,user_message,gold_answer
15809,75,MathArena/hmmt_feb_2025_outputs: 24,"To solve this problem, we need to determine th...","Please reason step by step, and put your final...",20
15810,25,MathArena/hmmt_feb_2025_outputs: 24,"To solve the problem, we need to determine the...","Please reason step by step, and put your final...",20
15811,60,MathArena/hmmt_feb_2025_outputs: 24,"To solve the problem, we need to understand th...","Please reason step by step, and put your final...",20
15816,sqrt(3),MathArena/hmmt_feb_2025_outputs: 7,"To solve for the unique triple \((a, b, c)\), ...","Please reason step by step, and put your final...",\frac{9 \sqrt{23}}{23}
15817,sqrt(2) + sqrt(3) + sqrt(5),MathArena/hmmt_feb_2025_outputs: 7,"To solve for the unique triple \((a, b, c)\) o...","Please reason step by step, and put your final...",\frac{9 \sqrt{23}}{23}
15818,3,MathArena/hmmt_feb_2025_outputs: 7,"To solve for the unique triple \((a, b, c)\) o...","Please reason step by step, and put your final...",\frac{9 \sqrt{23}}{23}
15819,1 + 3*sqrt(2)/2,MathArena/hmmt_feb_2025_outputs: 7,"To solve the problem, we begin by analyzing th...","Please reason step by step, and put your final...",\frac{9 \sqrt{23}}{23}
15820,"[-3,9]",MathArena/hmmt_feb_2025_outputs: 10,To solve for the possible values of \(a + b + ...,"Please reason step by step, and put your final...","\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}"
15821,"[-3,3]",MathArena/hmmt_feb_2025_outputs: 10,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...","\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}"
15822,"[9,-3]",MathArena/hmmt_feb_2025_outputs: 10,Let's start by using the given equations:\n\n\...,"Please reason step by step, and put your final...","\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}"
15823,"[13,0]",MathArena/hmmt_feb_2025_outputs: 10,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...","\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}"
15824,0,MathArena/hmmt_feb_2025_outputs: 6,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",\frac{1311}{2017}
15825,0,MathArena/hmmt_feb_2025_outputs: 6,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",\frac{1311}{2017}
15826,1/2017,MathArena/hmmt_feb_2025_outputs: 6,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",\frac{1311}{2017}
15827,0,MathArena/hmmt_feb_2025_outputs: 6,To find the remainder \( r \) when \( 2017^{20...,"Please reason step by step, and put your final...",\frac{1311}{2017}

In [73]:
df_new_false[df_new_false["unique_problem_label"]=="MathArena/brumo_2025_outputs: 7"]

Empty DataFrame
Columns: [Unnamed: 0, index, parsed_answer, correct, competition, unique_problem_label, problem_idx, output_cost_per_tokens, input_cost_per_tokens, cost, output_tokens, input_tokens, answer, user_message, idx_answer, model_config, model_name, gold_answer, ten_percent_quantile]
Index: []

In [74]:
df_new_false[df_new_false[CORRECT]==False]

,Unnamed: 0,index,parsed_answer,correct,competition,unique_problem_label,problem_idx,output_cost_per_tokens,input_cost_per_tokens,cost,output_tokens,input_tokens,answer,user_message,idx_answer,model_config,model_name,gold_answer,ten_percent_quantile
5868,5868,5868,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.007622,720.0,169.0,"To solve this problem, we need to analyze the ...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,248,2
5869,5869,5869,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.008783,836.0,169.0,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...",1,openai/gpt-4o,gpt-4o,248,2
5870,5870,5870,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.010582,1016.0,169.0,"To solve this problem, we begin by analyzing t...","Please reason step by step, and put your final...",2,openai/gpt-4o,gpt-4o,248,2
5871,5871,5871,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.010802,1038.0,169.0,"First, we need to analyze the sequence \( x_1,...","Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,248,2
5872,5872,5872,960,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 23,23,10.0,2.5,0.012202,1141.0,317.0,To determine when the greedy algorithm succeed...,"Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,610,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15823,15823,15823,"[13,0]",False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 10,10,10.0,2.5,0.010315,1003.0,114.0,"To solve the problem, we start by analyzing th...","Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,"\frac{-1+\sqrt{17}}{2}, \frac{-1-\sqrt{17}}{2}",3
15824,15824,15824,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.005293,512.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15825,15825,15825,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.006683,651.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",1,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15826,15826,15826,1/2017,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.007923,775.0,69.0,"To solve the problem, we need to find the rema...","Please reason step by step, and put your final...",2,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5
15827,15827,15827,0,False,MathArena/hmmt_feb_2025_outputs,MathArena/hmmt_feb_2025_outputs: 6,6,10.0,2.5,0.007313,714.0,69.0,To find the remainder \( r \) when \( 2017^{20...,"Please reason step by step, and put your final...",3,openai/gpt-4o,gpt-4o,\frac{1311}{2017},5

In [75]:
import textwrap
def prettify( f, col):
  text = df[col].iloc[0]  # e
  return  textwrap.fill(text, width=80)
print(prettify(example, "answer"))

Looking at this problem, I need to find the minimum number of rectangular tiles
needed to cover a $2025 \times 2025$ grid such that exactly one square in each
row and exactly one square in each column remains uncovered.  ## Understanding
the Configuration  Since each row has exactly one uncovered square and each
column has exactly one uncovered square, the uncovered squares form a
**permutation matrix**. If I denote the uncovered square in row $i$ as being in
column $\pi(i)$, then $\pi: \{1, 2, \ldots, 2025\} \to \{1, 2, \ldots, 2025\}$
must be a permutation (bijection).  The total number of uncovered squares is
exactly $2025$, and the number of covered squares is $2025^2 - 2025 = 2025
\times 2024$.  ## Analyzing a Tiling Strategy  Let me consider a **row-by-row
tiling strategy**:  For each row $i$: - The uncovered square is at position $(i,
\pi(i))$ - The covered squares in row $i$ form **contiguous segments**:   - If
$\pi(i) = 1$: one segment covering columns $[2, 2025]$ → **1 tile needed**   -
If $\pi(i) = 2025$: one segment covering columns $[1, 2024]$ → **1 tile needed**
- If $1 < \pi(i) < 2025$: two segments covering columns $[1, \pi(i)-1]$ and
$[\pi(i)+1, 2025]$ → **2 tiles needed**  Since $\pi$ is a permutation: - Exactly
1 row has $\pi(i) = 1$ - Exactly 1 row has $\pi(i) = 2025$ - Exactly $2025 - 2 =
2023$ rows have $1 < \pi(i) < 2025$  **Total tiles needed**: $1 + 1 + 2(2023) =
2 + 4046 = 4048$  ## Verifying This is Optimal  To show we can't do better than
$4048$ tiles, let me count the total number of **horizontal segments** (maximal
contiguous sequences of covered squares in a row):  $$\text{Total segments} = 2
+ 2(2023) = 4048$$  **Key observation**: Can a single tile cover complete
segments from multiple rows?  Consider a tile covering rows $[r_1, r_2]$ and
columns $[c_1, c_2]$. For this tile to fully cover a segment $[a, b]$ in row
$i$, we need $[a, b] = [c_1, c_2]$.  For two different rows $i$ and $j$ to have
identical segments: - If both have left segments: $[1, \pi(i)-1] = [1,
\pi(j)-1]$ implies $\pi(i) = \pi(j)$ - If both have right segments: $[\pi(i)+1,
2025] = [\pi(j)+1, 2025]$ implies $\pi(i) = \pi(j)$  But since $\pi$ is a
permutation with $i \neq j$, we must have $\pi(i) \neq \pi(j)$. This is a
contradiction!  Therefore, **no two segments in different rows can have the same
column range**, which means a single tile cannot completely cover segments from
two different rows. Each segment essentially requires its own dedicated tile (or
portion thereof).  Since we have $4048$ segments and each represents a distinct
covering requirement, we need **at least $4048$ tiles**.  ## Testing with the
Diagonal Configuration  To verify, consider $\pi(i) = i$ (diagonal uncovered
squares). We can tile using: - Tiles $T_i$ for $i = 1, \ldots, 2024$: row $i$,
columns $[i+1, 2025]$ (right segments) - Tiles $S_j$ for $j = 1, \ldots, 2024$:
column $j$, rows $[j+1, 2025]$ (covering left segments)  This gives exactly
$2024 + 2024 = 4048$ non-overlapping tiles.  Therefore, the minimum number of
tiles is $\boxed{4048}$.

In [76]:
print(prettify(df, "user_message"))

Please reason step by step, and put your final answer within \boxed{}.  Consider
a $2025 \times 2025$ grid of unit squares. Matilda wishes to place on the grid
some rectangular tiles, possibly of different sizes, such that each side of
every tile lies on a grid line and every unit square is covered by at most one
tile. Determine the minimum number of tiles Matilda needs to place so that each
row and each column of the grid has exactly one unit square that is not covered
by any tile.

In [77]:
len(df_new_false["unique_problem_label"].unique())

74

In [78]:
df_new_true = df_new[df_new[CORRECT]==True]
len(df_new_true["unique_problem_label"].unique())

16

In [79]:
problems_path = "data/all_problems_pd/all_problems.csv"
all_problems = pd.read_csv(problems_path)
mask = ~all_problems["unique_problem_label"].str.contains("kangaroo", case=False, na=False)
all_problems = all_problems[mask]

In [80]:
def select_problem_sample():
  """Here we just try to selct problems it could not answer"""
  problems_it_could_not_anwer = df_new_false["unique_problem_label"].unique()
  df = df_new_false
  difficulty_levels = list(df["ten_percent_quantile"].unique())
  selected_problems = []
  all_problems["unique_problem_label"] = all_problems["unique_problem_label"].map(lambda x: x.replace("-", "_"))
  df["unique_problem_label"] = df["unique_problem_label"].map(lambda x: x.replace("-", "_"))
  for lvl in difficulty_levels:
    # select a problem with this level 
    selected_problem= df[df["ten_percent_quantile"]==lvl].head(1)
    index = list(selected_problem["unique_problem_label"])[0]
    index = index.replace("_outputs", "").replace("-", "_")
    
    problem = all_problems[all_problems["unique_problem_label"]==index].iloc[0]["problem"]

    selected_problem["problem"] = problem

    selected_problems.append(selected_problem)
    
  return pd.concat(selected_problems)

selected_problems = select_problem_sample()
selected_problems

,Unnamed: 0,index,parsed_answer,correct,competition,unique_problem_label,problem_idx,output_cost_per_tokens,input_cost_per_tokens,cost,output_tokens,input_tokens,answer,user_message,idx_answer,model_config,model_name,gold_answer,ten_percent_quantile,problem
5868,5868,5868,3,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 28,28,10.0,2.5,0.007622,720.0,169.0,"To solve this problem, we need to analyze the ...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,248,2,"Let $x_1, x_2, x_3, \ldots$ be a sequence of r..."
5872,5872,5872,960,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 23,23,10.0,2.5,0.012202,1141.0,317.0,To determine when the greedy algorithm succeed...,"Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,610,5,"From an unlimited supply of $1$-cent coins, $1..."
5876,5876,5876,137,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 27,27,10.0,2.5,0.010075,936.0,286.0,"To solve this problem, we need to analyze the ...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,19,6,Let $A_1 A_2 A_3 \ldots A_{11}$ be an $11$-sid...
5884,5884,5884,79,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 19,19,10.0,2.5,0.008738,818.0,223.0,"To solve the given product, we start by simpli...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,106,7,The product\n$$\prod_{k=4}^{63} \frac{\log_k \...
5892,5892,5892,2,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 11,11,10.0,2.5,0.010095,882.0,510.0,"To solve this problem, we need to find the int...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,259,4,A piecewise linear function is defined by\n\[f...
5912,5912,5912,42,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 14,14,10.0,2.5,0.005618,521.0,163.0,"To solve this problem, we need to find the min...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,60,1,"Let $ABCDE$ be a convex pentagon with $AB=14$,..."
5980,5980,5980,59,False,MathArena/aime_2025_outputs,MathArena/aime_2025_outputs: 10,10,10.0,2.5,0.009430,858.0,340.0,"To solve this problem, we need to determine th...","Please reason step by step, and put your final...",0,openai/gpt-4o,gpt-4o,81,3,The $27$ cells of a $3 \times 9$ grid are fill...

In [81]:
all_problems[all_problems["unique_problem_label"] == "MathArena/kangaroo_2025_1_2: 9"]
# selected_problems["unique_problem_label"]

Empty DataFrame
Columns: [Unnamed: 0, problem_idx, problem, answer, source, __index_level_0__, unique_problem_label, competition, problem_type, points, grading_scheme, sample_solution, sample_grading, image]
Index: []

In [83]:
data_path = "data/selected_problems/gpt5mini_8problems.csv"
selected_problems.to_csv(data_path)